/**
 * Writes src/lib/build-stamp.ts before vite build so each production build
 * produces a tracked file change (avoids empty commits when only dist changed).
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const out = path.join(__dirname, "..", "src", "lib", "build-stamp.ts");
const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "package.json"), "utf8"));
let sha = "local";
try {
  sha = execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
} catch {
  /* not a git checkout */
}
const stamp = new Date().toISOString();
const content = `/** Auto-generated by scripts/stamp-build.cjs - do not edit. */
export const BUILD_STAMP = ${JSON.stringify(stamp)};
export const GIT_SHA = ${JSON.stringify(sha)};
export const APP_VERSION = ${JSON.stringify(pkg.version)};
`;
fs.writeFileSync(out, content, "utf8");
console.log("[stamp-build]", stamp, sha, pkg.version);
