export const URL_OPTIMIZER_RESOLVE_CHUNK_SIZE = 50;
export const URL_OPTIMIZER_CONTENT_CHUNK_SIZE = 40;
export const URL_OPTIMIZER_AGENT_BATCH_SIZE = 10;
export const URL_OPTIMIZER_AGENT_CONCURRENCY = 2;
export const URL_OPTIMIZER_AGENT_MAX_RETRIES = 3;
export const URL_OPTIMIZER_AGENT_MAX_TOKENS = 4096;
export const URL_OPTIMIZER_BODY_EXCERPT_MAX = 1500;
export const URL_OPTIMIZER_BLOG_PATH = "blog";
